apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: springboot

  template:
    metadata:
      labels:
        app: springboot

    spec:
      containers:
      - name: springboot-container
        image: user-service
        imagePullPolicy: Never

        ports:
        - containerPort: 8080

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/userdb

        - name: SPRING_DATASOURCE_USERNAME
          value: root

        - name: SPRING_DATASOURCE_PASSWORD
          value: root123